### ISSUE TITLE
Some sprites cant open with normal software(Like sprview)

### ISSUE THREAD

**Issue by Sayu233** [Blaperture-Mesa/cso-pak-extracted#1]

**Comment by cso-idn-player** [comment]
Because newer sprites are not goldsrc-compatible format.
The sprite frames are actually in .DDS format.

Build this project to preview them.
https://gitlab.com/an-cso-projects/HL-Texture-Tools/-/tree/spr-v3-support

**Comment by Sayu233** [comment]
Solved.Thanks
